# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('winner', models.BooleanField()),
                ('miss_congeniality', models.BooleanField()),
                ('quote', models.CharField(max_length=500)),
                ('image_url', models.CharField(max_length=500)),
            ],
        ),
    ]
